In [158]:
import numpy as np

In [159]:
# List vs numpy
from time import process_time

In [160]:
# time taken by list
my_list = [x for x in range(10000)]
start_time = process_time()

my_list = [i+5 for i in my_list]

end_time = process_time()

print(end_time - start_time)


0.0008026359999995236


In [161]:
# time taken by numpy

np_array = np.array([x for x in range(10000)])
start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)


0.00027126899999974086


In [162]:
np_arr = np.array([1,2,3,4,5])
print(np_arr)
type(np_arr)

[1 2 3 4 5]


numpy.ndarray

In [163]:
# one dimensional array
a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [164]:
# two dimensional array
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [165]:
# three dimensional array
c = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(c)
c.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [166]:
# with dtype
d = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(d)
d.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

In [167]:
# initial placeholders
# create numpy array of zeros == (4,5) means 4 rows and 5 columns
e = np.zeros((4,5))
print(e)
e.shape

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(4, 5)

In [168]:
# numpy array with all values as 1s
y = np.ones((3,3),dtype=int)
print(y)
y.shape

[[1 1 1]
 [1 1 1]
 [1 1 1]]


(3, 3)

In [169]:
# array of a particular value (5,4)-is the shape(row,col) and 8 is the number we use in array
z = np.full((5,4), 8)
print(z)
z.shape

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


(5, 4)

In [170]:
#create an identity matrix, here the number of rows and columns should be equal
i = np.eye(5)
print(i)
i.shape

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


(5, 5)

In [171]:
# create numpy array with random values
# by defualt values will be between 0 and 1
g = np.random.random((3,4))
print(g)
g.shape

[[0.1045     0.3401992  0.08107772 0.73667464]
 [0.77452194 0.18236631 0.15749312 0.57945442]
 [0.84429708 0.75967054 0.15686745 0.14381967]]


(3, 4)

In [172]:
# random integer values array within a specific range
# mention the range eg 10 to 100
# and finally the shape e.g (3,5)
f = np.random.randint(10,100,(3,5))
print(f)
f.shape

[[26 40 36 15 76]
 [70 16 56 47 40]
 [49 38 89 41 59]]


(3, 5)

In [173]:
# create array of evenly spaced values
# 10to30 is range
# here 5 is the number of values I need
r = np.linspace(10,30,5)
print(r)
r.shape

[10. 15. 20. 25. 30.]


(5,)

In [174]:
# array of evenly spaced values with a specific step number
# here 5 is the step value
s = np.arange(10,30,3)
print(s)
s.shape


[10 13 16 19 22 25 28]


(7,)

In [175]:
#convert list to numpy array

list1 = [10,20,30,40,50,60]
n_arr = np.asarray(list1)
print(n_arr)
type(n_arr)

[10 20 30 40 50 60]


numpy.ndarray

In [176]:
# analyzing numpy array
cd = np.random.randint(10,90,(5,5))
print(cd)

[[14 81 69 45 20]
 [28 20 66 70 89]
 [14 75 54 45 42]
 [29 65 10 35 75]
 [50 86 28 19 64]]


In [177]:
# get array dimension
print(cd.shape)

#number of dimensions
print(cd.ndim)

# check number of elements in an array
print(cd.size)

# check data type of values in the array
print(cd.dtype)

(5, 5)
2
25
int64


In [178]:
# Mathematical operations on numpy array
ad = np.array([1,2,3,4])
bd = np.array([5,6,7,8])

sum = ad + bd
print(sum)

[ 6  8 10 12]


In [179]:
print(ad-bd)

[-4 -4 -4 -4]


In [180]:
print(ad*bd)

[ 5 12 21 32]


In [181]:
print(ad/bd)

[0.2        0.33333333 0.42857143 0.5       ]


In [182]:
ad = np.array([4,6,7,8])
bd = np.array([9,10,2,3])

print(np.add(ad,bd))

print(np.subtract(ad,bd))

print(np.multiply(ad,bd))

print(np.divide(ad,bd))


[13 16  9 11]
[-5 -4  5  5]
[36 60 14 24]
[0.44444444 0.6        3.5        2.66666667]


In [183]:
# Array manipulation

arr = np.random.randint(0,10,(2,3))
print(arr)
print(arr.shape)

[[6 6 6]
 [4 5 1]]
(2, 3)


In [184]:
# transpose of matrix
trans = np.transpose(arr)
print(trans)

[[6 4]
 [6 5]
 [6 1]]


In [185]:
arr = np.random.randint(0,10,(2,3))
print(arr)
print(arr.shape)

[[1 2 1]
 [8 9 8]]
(2, 3)


In [186]:
#method 2 to find transpose, just add the T and it will transpose the arr
trans2 = arr.T
print(trans2)
print(trans2.shape)


[[1 8]
 [2 9]
 [1 8]]
(3, 2)


In [187]:
# reshaping array

ar = np.random.randint(0,10,(2,3))
print(ar)
print(ar.shape)

[[4 3 8]
 [3 2 9]]
(2, 3)


In [188]:
# reshape to (3,2) array
ar2 = ar.reshape(3,2)
print(ar2)
print(ar2.shape)

[[4 3]
 [8 3]
 [2 9]]
(3, 2)


In [189]:
# Introducing Pandas for data processing and analysis
import pandas as pd

In [190]:
#importing the boston house price data from sklearn
from sklearn.datasets import load_boston

In [191]:
boston_dataset = load_boston()

In [192]:
type(boston_dataset)

sklearn.utils.Bunch

In [193]:
print(boston_dataset)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

In [194]:
# pandas dataframe

boston_df = pd.DataFrame(boston_dataset['data'],
                        columns = boston_dataset['feature_names'])
print(boston_df.head())

      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33  


In [195]:
boston_df.shape

(506, 13)

In [196]:
# import pandas dataframe from csv
diabetes_df = pd.read_csv('diabetes.csv')
type(diabetes_df)

pandas.core.frame.DataFrame

In [197]:
print(diabetes_df.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [198]:
diabetes_df.shape

(768, 9)

In [199]:
# read excel files
poke_df = pd.read_excel('pokemon_data.xlsx')
poke_df.head()

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

In [200]:
# Exporting dataframe to csv file
#using boston df

boston_df.to_csv('boston.csv',index=False)

In [201]:
#checking the file
b_df = pd.read_csv('boston.csv')
b_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [202]:
# for excel use, to_excel command

In [203]:
#create datafram with random values, 20,10 is the shape
random_df = pd.DataFrame(np.random.rand(20,10))
random_df.head()


0         1         2         3         4         5         6  \
0  0.220822  0.048259  0.829402  0.701028  0.277892  0.706249  0.587502   
1  0.163496  0.983628  0.064962  0.683845  0.007632  0.756742  0.568162   
2  0.638866  0.918987  0.387837  0.158936  0.615150  0.148949  0.958967   
3  0.775144  0.616300  0.411037  0.559970  0.751817  0.525193  0.729840   
4  0.208422  0.937817  0.775282  0.419923  0.507079  0.730901  0.978874   

          7         8         9  
0  0.288087  0.087060  0.808105  
1  0.708089  0.339094  0.063399  
2  0.687032  0.134115  0.696823  
3  0.227038  0.735500  0.548956  
4  0.286706  0.904065  0.449013

In [204]:
# inspecting dataframe


In [205]:
#find the number of rows and columns
boston_df.shape

(506, 13)

In [206]:
# first five rows
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [207]:
# information about the dataframe
boston_df.info()

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

In [ ]:
# find number of missing values in each column
boston_df.isnull().sum()

In [ ]:
#counting values based on the labels

diabetes_df.value_counts('Outcome')

In [ ]:
# group values based on the mean
diabetes_df.groupby('Outcome').mean()

In [ ]:
# Statistical Measures

#count number of values in each column

boston_df.count()

In [ ]:
# mean value
boston_df.mean()

In [ ]:
# standard deviation

boston_df.std()

In [ ]:
# minimum value
boston_df.min()

In [ ]:
# maximum value
boston_df.max()

In [ ]:
# to get all the statistical measures in a single command use describe
boston_df.describe()

In [ ]:
# Manipulate a DataFrame

# adding a column to dataframe
boston_df['Price'] = boston_dataset.target
boston_df.head()

In [ ]:
#removing a particular row
boston_df.drop(index=0,axis=0)

In [ ]:
#removing a particular column
boston_df.drop(columns='ZN',axis=1)

In [ ]:
#locate particular row using index value

boston_df.iloc[2]

In [ ]:
# locate a particular column
print(boston_df.iloc[:,0]) #print first column
print(boston_df.iloc[:,1]) #second column
print(boston_df.iloc[:,2]) #third column

print(boston_df.iloc[:,-1]) #last column


In [ ]:
# Correlation: Aims at finding the relationship between the various columns in dataset
# 1. Positive Correlation - one value increases, then the other also increases
# 2. Negative Correlation - one value increases, then the other decreases


In [ ]:
boston_df.corr()

In [ ]:
# Matplotlib library for making plots and graphs
#4:30

In [209]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np


In [210]:
x = np.linspace(0,10,100)
y = np.sin(x)
z = np.cos(x)

In [211]:
print(x)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [ ]:
print(y)

In [ ]:
print(z)

In [ ]:
#plotting the data

In [ ]:
# sine wave
plt.plot(x,y)
plt.show()

In [ ]:
# cos sine wave
plt.plot(x,z)
plt.show()

In [ ]:
# adding title x axis and y axis labels

In [ ]:
plt.plot(x,y)
plt.xlabel("Angle")
plt.ylabel("Sine value")
plt.title("Sine Wave")
plt.show()

In [ ]:
# plot a parabola
x = np.linspace(-10,10,20)
y = x**2
plt.plot(x,y)
plt.show()

In [ ]:
plt.plot(x, y, 'r+')
plt.show()

In [ ]:
plt.plot(x,y, 'g.')
plt.show()

In [ ]:
plt.plot(x,y, 'rx')
plt.show()

In [ ]:
x = np.linspace(-5,5,50)
plt.plot(x,np.sin(x), 'g-')
plt.plot(x,np.cos(x), 'r--')
plt.show()

In [ ]:
#Bar plot
#creating an empty figure
fig = plt.figure()
# adding axis to it
#first zeros represent the coordinates, and the ones the width and height of the rectangle
ax = fig.add_axes([0,0,1,1])
langs = ['English','Spanish','Shona','Latin','French']
people = [100,40,150,20,10]
ax.bar(langs,people)
plt.xlabel('Languages')
plt.ylabel('No of people')
plt.show()


In [ ]:
# pie chart
fig1 = plt.figure()
ax = fig1.add_axes([0,0,1,1])
langs = ['English','Spanish','Shona','Latin','French']
people = [100,40,150,20,10]
#autopct specifies the number of decimal points we need
# %1.1f%% means we need one decimal place / floating point after 1.
ax.pie(people, labels=langs, autopct='%1.1f%%')
plt.show()

In [ ]:
# scatter plot
x = np.linspace(0,10,30)
y = np.sin(x)
z = np.cos(x)
fig2 = plt.figure()
ax = fig2.add_axes([0,0,1,1])
ax.scatter(x,y, color='g')
ax.scatter(x,z, color='r')
plt.show()

In [208]:
#3d scatter plot
from mpl_toolkits.mplot3d import Axes3D
fig3 = plt.figure()
ax = plt.gca(projection='3d')
z = 20 * np.random.random(100)
x = np.sin(z)
y = np.cos(z)
ax.scatter(x,y,z, c=z,cmap='Reds')
plt.show()

NameError: name 'plt' is not defined